version: '3.9'

services:
    mongodb:
        image: mongo:6.0.2
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        ports:
            - 27017:27017
        volumes:
            - db:/data/db

app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_api
    container_name: app_api
    env_file: ./.env
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./:/data/www/app_api
    environment:
        - MONGO_URI=$MONGO_URI
        - PORT=$PORT
        - JWT_SECRET=$JWT_SECRET
        - MONGO_USER=$MONGO_USER
        - MONGO_PASSWORD=$MONGO_PASSWORD
        - MONGO_DATABASE_NAME=$MONGO_DATABASE_NAME
    ports:
        - 3000:3000
        - 8000:8000
    depends_on:
      - mongodb

volumes:
    db:
