version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-social-network
    container_name: backend-social-network
    restart: always
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./:/data/www/backend-social-network
    networks:
      - api-network
    ports:
      - '8000:8000'
    depends_on:
      - mysql
      - memcached
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - api-network
    ports:
      - '3306:3306'
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: db
      MYSQL_USER: thangdx
      MYSQL_PASSWORD: thangdx@1234

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234

  redis:
    image: "redis:alpine"
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - data-volume
    networks:
      - api-network

  memcached:
    image: 'memcached:latest'
    restart: unless-stopped
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
volumes:
  data-volume:
    driver: local
